// <auto-generated />
using AggregationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggregationApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221124145804_tablePresicionScaleChanged")]
    partial class tablePresicionScaleChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AggregationApp.Models.AggregatedElectricity", b =>
                {
                    b.Property<string>("TINKLAS")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Pminus")
                        .HasPrecision(14, 6)
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("Pplus")
                        .HasPrecision(14, 6)
                        .HasColumnType("decimal(14,6)");

                    b.HasKey("TINKLAS");

                    b.ToTable("AggregatedElectricities");
                });
#pragma warning restore 612, 618
        }
    }
}
