// <auto-generated />
using System;
using AggregationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggregationApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221124055257_AddAggregatedElectricity")]
    partial class AddAggregatedElectricity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AggregationApp.Models.AggregatedElectricity", b =>
                {
                    b.Property<decimal?>("Pminus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pplus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TINKLAS")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AggregatedElectricities");
                });
#pragma warning restore 612, 618
        }
    }
}
